const quizQuestions = [
    {
        id: 1,
        textStructure: [{w: "下列", p: "xià liè"}, {w: "句子", p: "jù zi"}, "中，", {w: "成语", p: "chéng yǔ"}, "“", {w: "不求甚解", p: "bù qiú shèn jiě"}, "”", {w: "在文中的", p: "zài wén zhōng de"}, {w: "古典原意", p: "gǔ diǎn yuán yì"}, {w: "是", p: "shì"}, "？"],
        en: "What is the original classical meaning of 'bù qiú shèn jiě' in this text?",
        options: [
            { textStructure: [{w: "读书", p: "dú shū"}, {w: "非常马虎", p: "fēi cháng mǎ hu"}, "，", {w: "不作任何", p: "bú zuò rèn hé"}, {w: "认真的思考", p: "rèn zhēn de sī kǎo"}], en: "Reading carelessly without any real thinking.", correct: false, explanationStructure: [{w: "错误", p: "cuò wù"}, "，", {w: "这是现代汉语的", p: "zhè shì xiàn dài hàn yǔ de"}, {w: "贬义贬称", p: "biǎn yì biǎn chēng"}, "，", {w: "不是陶渊明的", p: "bú shì táo yuán míng de"}, {w: "读书态度", p: "dú shū tài du"}, "。"], explanationEn: "Incorrect. describing careless reading is its modern corrupted meaning, not Tao's original intent." },
            { textStructure: [{w: "读书时", p: "dú shū shí"}, {w: "只求理解", p: "zhǐ qiú lǐ jiě"}, {w: "核心大意和精神", p: "hé xīn dà yì hé jīng shén"}, "，", {w: "不在死字句上", p: "bú zài sǐ zì jù shàng"}, {w: "过分钻研", p: "guò fèn zuān yán"}], en: "Focusing on capturing the inner essence rather than over-analyzing every single word.", correct: true, explanationStructure: [{w: "正确", p: "zhèng què"}, "，", {w: "五柳先生读书", p: "wǔ lǔ xiān sheng dú shū"}, {w: "重在精神共鸣", p: "zhòng zài jīng shén gòng míng"}, "，", {w: "不当死记硬背的", p: "bú dàng sǐ jì yìng bèi de"}, "“", {w: "书呆子", p: "shū dāi zi"}, "”", "。"], explanationEn: "Correct. Classical '不求甚解' is a positive method: understanding the grand theme and spirit without getting stuck in excessive grammatical details." },
            { textStructure: [{w: "因为记忆力差", p: "yīn wèi jì yì lì chà"}, "，", {w: "读完书后", p: "dú wán shū hòu"}, {w: "无法理解含义", p: "wú fǎ lǐ jiě hán yì"}], en: "Failing to comprehend due to poor memory capacity.", correct: false, explanationStructure: [{w: "错误", p: "cuò wù"}, "，", {w: "带入文意", p: "dài rù wén yì"}, {w: "完全说不通", p: "wán quán shuō bù tōng"}, "。"], explanationEn: "Incorrect. This makes the sentence completely ungrammatical and illogical here." },
            { textStructure: [{w: "只看图画", p: "zhǐ kàn tú huà"}, "，", {w: "不看任何", p: "bú kàn rèn hé"}, {w: "文字注解", p: "wén zì zhù jiě"}], en: "Only looking at book illustrations while ignoring all characters.", correct: false, explanationStructure: [{w: "胡说", p: "hú shuō"}, "，", {w: "古代书籍", p: "gǔ dài shū jí"}, {w: "极少有图画", p: "jí shǎo yǒu tú huà"}], explanationEn: "Incorrect. Ancient scrolls contained pure characters and rarely featured paintings or drawings." }
        ]
    },
    {
        id: 2,
        textStructure: [{w: "文中", p: "wén zhōng"}, "“", {w: "造饮辄尽，期在必醉", p: "zào yǐn zhé jìn qī zài bì zuì"}, "”", {w: "中的", p: "zhōng de"}, "“", {w: "造", p: "zào"}, "”", {w: "字正确的", p: "zì zhèng què de"}, {w: "词义是", p: "cí yì shì"}, "？"],
        en: "What does the character 'zào' mean in this musical/drinking sentence?",
        options: [
            { textStructure: [{w: "制造", p: "zhì zào"}, "、", {w: "酿造好酒", p: "niàng zào hǎo jiǔ"}], en: "To manufacture or brew fresh wine.", correct: false, explanationStructure: [{w: "错误", p: "cuò wù"}, "，", {w: "这是现代汉语的", p: "zhè shì xiàn dài hàn yǔ de"}, {w: "工业意思", p: "gōng yè yì si"}, "。"], explanationEn: "Incorrect. This mistakes it for the modern industrial term of brewing or manufacturing." },
            { textStructure: [{w: "动词", p: "dòng cí"}, "，“", {w: "往", p: "wǎng"}, "””、基“", {w: "到……去", p: "dào qù"}, "”"], en: "A verb, meaning 'to go to' or 'to visit'.", correct: true, explanationStructure: [{w: "正确", p: "zhèng què"}, "，“", {w: "造饮", p: "zào yǐn"}, "”", {w: "就是“去喝酒”", p: "jiù shì qù hē jiǔ"}, "，", {w: "这是非常高频的", p: "zhè shì fēi cháng gāo pín de"}, {w: "文言词汇考点", p: "wén yán cí huì kǎo diǎn"}, "。"], explanationEn: "Correct. In classical text, 'zào' means to go to or visit. '造饮' means he physically went to where the wine was provided." },
            { textStructure: [{w: "编造", p: "biān zào"}, "、", {w: "说谎话", p: "shuō huǎng huà"}], en: "To fabricate lies or fake news.", correct: false, explanationStructure: [{w: "字意错误", p: "zì yì cuò wù"}, "。"], explanationEn: "Incorrect. This meaning is completely irrelevant to the context of drinking with friends." },
            { textStructure: [{w: "迎接", p: "yíng jiē"}, "、", {w: "招待客人", p: "zhāo dài kè rén"}], en: "To welcome or entertain guests.", correct: false, explanationStructure: [{w: "方向完全颠倒", p: "fāng xiàng wán quán diān dǎo"}, "，", {w: "他是客人", p: "tā shì kè rén"}, "，", {w: "不是主人", p: "bú shì zhǔ rén"}, "。"], explanationEn: "Incorrect. He was the guest going out to drink, not the host welcoming visitors." }
        ]
    },
    {
        id: 3,
        textStructure: [{w: "下列", p: "xià liè"}, {w: "成语", p: "chéng yǔ"}, "中，", {w: "哪一个", p: "nǎ yí gè"}, {w: "不能用来", p: "bù néng yòng lái"}, {w: "形容五柳先生的", p: "xíng róng wǔ lǔ xiān sheng de"}, {w: "物质生活贫困", p: "wù zhì shēng huó pín kùn"}, "？"],
        en: "Which of the following idioms CANNOT describe Wuliu's poor physical life?",
        options: [
            { textStructure: [{w: "环堵萧然", p: "huán dǔ xiāo rán" }], en: "Huán Dǔ Xiāo Rán (empty walls).", correct: false, explanationStructure: [{w: "错误", p: "cuò wù"}, "，", {w: "环堵萧然形容", p: "huán dǔ xiāo rán xíng róng"}, {w: "他的房子非常破旧简陋", p: "tā de fáng wū fēi cháng pò jiù jiǎn lòu"}, "。"], explanationEn: "Incorrect. This phrase explicitly details his empty, cold, and poorly sheltered rooms." },
            { textStructure: [{w: "短褐穿结", p: "duǎn hè chuān jié" }], en: "Duǎn Hè Chuān Jié (patched clothes).", correct: false, explanationStructure: [{w: "错误", p: "cuò wù"}, "，", {w: "短褐穿结形容", p: "duǎn hè chuān jié xíng róng"}, {w: "他的衣服破洞打满补丁", p: "tā de yī fu pò dòng dǎ mǎn bǔ dīng"}, "。"], explanationEn: "Incorrect. This idiom illustrates his poverty through his torn, patched布衣 garments." },
            { textStructure: [{w: "箪瓢屡空", p: "dān piáo lǚ kōng" }], en: "Dān Piáo Lǚ Kōng (empty bowls).", correct: false, explanationStructure: [{w: "错误", p: "cuò wù"}, "，", {w: "箪瓢屡空形容", p: "dān piáo lǚ kōng xíng róng"}, {w: "他经常挨饿断粮", p: "tā jīng cháng ái è duàn liáng"}, "。"], explanationEn: "Incorrect. This directly states that his food and water containers were frequently empty." },
            { textStructure: [{w: "欣然忘食", p: "xīn rán wàng shí" }], en: "Xīn Rán Wàng Shí (happily forgetting food).", correct: true, explanationStructure: [{w: "正确", p: "zhèng què"}, "，“", {w: "欣然忘食", p: "xīn rán wàng shí"}, "”", {w: "是他读书获得精神快乐后的", p: "shì tā dú shū huò dé jīng shén kuài lè hòu de"}, {w: "专注专注表现", p: "zhuān zhù biǎo xiàn"}, "，", {w: "不是穷困", p: "bú shì qióng kùn"}, "。"], explanationEn: "Correct. This phrase highlights his supreme happiness and spiritual satisfaction from books, not his lack of wealth." }
        ]
    },
    {
        id: 4,
        textStructure: [{w: "赞语中", p: "zàn yǔ zhōng"}, "“", {w: "不戚戚于贫贱，不汲汲于富贵", p: "bú qī qī yú pín jiàn bù jí jí yú fù guì"}, "”", {w: "展现了", p: "zhǎn xiàn le"}, {w: "怎样的人生态度", p: "zěnyàng de rén shēng tài du"}, "？"],
        en: "What life mindset does the quote '不戚戚于贫贱，不汲汲于富贵' show?",
        options: [
            { textStructure: [{w: "逃避现实", p: "táo bì xiàn shí"}, "、", {w: "极度消极的", p: "jí dù xiāo jí de"}, {w: "悲观思想", p: "bēi guān sī xiǎng"}], en: "A cowardly, pessimistic escape from real life.", correct: false, explanationStructure: [{w: "错误", p: "cuò wù"}, "，", {w: "这是高尚的", p: "zhè shì gāo shàng de"}, {w: "高尚傲骨", p: "gāo shàng ào gǔ"}, "，", {w: "绝非软弱", p: "jué fēi ruǎn ruò"}, "。"], explanationEn: "Incorrect. This is an elite stance of philosophical calmness and inner pride, not cowardly crying." },
            { textStructure: [{w: "甘愿受苦", p: "gān yuàn shòu kǔ"}, "，", {w: "希望早日", p: "xī wàng zǎo rì"}, {w: "获得朝廷的高官高薪", p: "huò dé cháo tíng de gāo guān gāo xīn"}], en: "Suffering patiently while hoping for a future promotion.", correct: false, explanationStructure: [{w: "功利错误", p: "gōng lì cuò wù"}, "，", {w: "他一生拒绝做官", p: "tā yì shēng jù jué zuò guān"}, "。"], explanationEn: "Incorrect. Tao famously resigned from office and refused to serve royal masters for money." },
            { textStructure: [{w: "安贫乐道", p: "ān pín lè dào"}, "、", {w: "忘怀得失的", p: "wàng huái dé shī de"}, {w: "超脱与豁达", p: "chāo tuō yǔ huò dá"}], en: "Being content with poverty, ignoring gains/losses, and staying mentally free.", correct: true, explanationStructure: [{w: "正确", p: "zhèng què"}, "，", {w: "不为贫穷忧虑", p: "bù wèi pín qióng yōu lǜ"}, "，", {w: "不追求富贵利禄", p: "bù zhuī qiú fù guì lì lù"}, "，", {w: "是真正懂得生命价值的境界", p: "shì zhēn zhèng dǒng de shēng mìng jià zhí de jìng jiè"}, "。"], explanationEn: "Correct. It perfectly defines his philosophical freedom: not worrying over bills or low social ranks, and refusing to flatter elites for quick fortunes." },
            { textStructure: [{w: "非常喜欢积攒财富", p: "fēi cháng xǐ huan jī zǎn cái fù"}], en: "An intense greed for collecting dark gold coins.", correct: false, explanationStructure: [{w: "胡扯", p: "hú chě"}, "。"], explanationEn: "Incorrect. This option completely runs opposite to the core virtue of the lesson." }
        ]
    },
    {
        id: 5,
        textStructure: [{w: "文章结尾", p: "wén zhāng jié wěi"}, {w: "连续使用两次", p: "lián xù shǐ yòng liǎng cì"}, "“", {w: "……之民欤？", p: "... zhī mín yú"}, "”", {w: "这一反问句", p: "zhè yí fǎn wèn jù"}, {w: "是为了表明", p: "shì wèi le biǎo míng"}, "？"],
        en: "Why did the text use the phrase '... zhī mín yú?' twice at the very end?",
        options: [
            { textStructure: [{w: "表明五柳先生", p: "biǎo míng wǔ lǔ xiān sheng"}, {w: "没有任何国籍", p: "méi yǒu rèn hé guó jí"}, "，", {w: "是个流浪汉", p: "shì gè liú làng hàn"}], en: "To state that Wuliu was a homeless refugee without citizenship.", correct: false, explanationStructure: [{w: "错误", p: "cuò wù"}, "，", {w: "这是文学赞叹", p: "zhè shì wén xué zàn tàn"}, "，", {w: "不是登记户口", p: "bú ... i dēng jì hù kǒu"}, "。"], explanationEn: "Incorrect. This is high artistic romance and praise, not a standard police immigration record." },
            { textStructure: [{w: "赞美五柳先生", p: "zàn měi wǔ lǔ xiān sheng"}, {w: "思想淳朴超脱", p: "sī xiǎng chún pǔ chāo tuō"}, "，", {w: "活得像上古理想社会的", p: "huó de xiàng shàng gǔ lǐ xiǎng shè huì de"}, {w: "快乐百姓一样", p: "kuài lè bǎi xìng yí yàng"}], en: "To praise his peaceful mind as being like that of ancient utopian citizens.", correct: true, explanationStructure: [{w: "正确", p: "zhèng què"}, "，", {w: "无怀氏和葛天氏", p: "wú huái shì hé gě tiān shì"}, {w: "都是传说中淳朴幸福的", p: "dōu shì chuán shuō zhōng chún pǔ xìng fú de"}, {w: "黄金乌托邦", p: "huáng jīn wū tuō bāng"}, "，", {w: "暗示他的境界超越了凡尘", p: "àn shì tā de jìng jiè chāo yuè le fán chén"}, "。"], explanationEn: "Correct. Both historical clans represent mythical, pure ancient golden ages where people lived without stress or greed. It states Wuliu's soul belongs to that heavenly world." },
            { textStructure: [{w: "抱怨当时的政府", p: "bào yuàn dāng shí de zhèng fǔ"}, {w: "不给平民发放福利", p: "bù gěi píng mín fā fàng fú lì"}], en: "To protest that the state failed to hand out monthly welfare checks.", correct: false, explanationStructure: [{w: "离题太远", p: "lí tí tài yuǎn"}, "。"], explanationEn: "Incorrect. This mistakes an elite literary metaphor for a modern political protest about cash aid." },
            { textStructure: [{w: "说明他非常崇拜", p: "shuō míng tā fēi cháng chóng bài"}, {w: "这两个少数民族的国王", p: "zhè liǎng gè shǎo shù mín zú de guó wáng"}], en: "To show he worshipped the military kings of these two minority tribes.", correct: false, explanationStructure: [{w: "常识错误", p: "cháng shí cuò wù"}, "。"], explanationEn: "Incorrect. These names represent symbolic primordial eras of absolute peace, not aggressive real-life tribal rulers." }
        ]
    }
];
